### ISSUE TITLE
errors with ONT

### ISSUE THREAD

**Issue by dinovski** [HaploKit/vechat#15]
vechat no longer appears available through conda.

I managed to install from source but got the following errors with ONT reads:
vechat ONT.fastq.gz -t 8 --platform ont -o ONT.vechat.corrected.fa 

[ 14%] Built target edlib
[ 42%] Built target spoa
[ 85%] Built target vechat_racon
[100%] Built target vechat_racon_exe
Performing the 1 iteration for error correction...
thread 'main' panicked at 'File is probably empty: FileTooShort', src/file.rs:30:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
perform variation graph based (haplotype-aware) error correction
[racon::Polisher::initialize] loaded target sequences 76.695651 s
[racon::Polisher::initialize] loaded sequences 70.578166 s
[racon::Polisher::initialize] error: empty overlap set!
Performing the 2 iteration for error correction...
thread 'main' panicked at 'File is probably empty: FileTooShort', src/file.rs:30:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
perform linear sequence based error correction
[racon::Polisher::initialize] error: empty target sequences set!

**Comment by kuma-gorou** [comment]
Hi, dinovski!
I got same error with ONT reads.
Have you solved the problem?
